# Generated by Django 3.2 on 2022-10-28 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
